[package]
name = "rust-yaml"
version = "0.1.0"
authors = ["jvalk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.4"
serde_yaml = "0.8.13"